name: glasnik
description: Secure mesh communication app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  go_router: ^14.8.0
  cryptography: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  just_audio: ^0.9.46
  mobile_scanner: ^6.0.6
  qr_flutter: ^4.1.0
  camera: ^0.11.1
  qr_code_scanner: ^1.0.1
  nearby_connections: ^4.2.0
  flutter_blue_plus: ^1.35.3
  cupertino_icons: ^1.0.6
  uuid: ^4.3.3
  crypto: ^3.0.3
  sim_data: ^0.2.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/ 